"""
Real Agent Workflow Example - Software Development Pipeline

This example demonstrates using real agents (Claude) with:
- Individual workspaces managed by WorkspaceManager
- AGENT.md configuration generated by AgentTemplate
- Skills loaded and managed by SkillManager
- SharedBoard for agent-to-agent communication

Agents:
1. Product Manager - Writes PRD
2. Developer - Implements based on PRD
3. Code Reviewer - Reviews the implementation

Prerequisites:
- tmux installed
- Claude CLI installed and authenticated
- ACF v2 installed: pip install -e /path/to/acf-v2

Usage:
    export ANTHROPIC_API_KEY=your_key
    python real_agent_workflow.py
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

# Add acf-v2 to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from acf.adapter.factory import AdapterFactory, create_claude_adapter
from acf.workflow.builder import WorkflowBuilder, END
from acf.workflow.runner import WorkflowRunner, WorkflowEventType

# Import real agent modules from core framework
from acf.agent import AgentTemplate, WorkspaceManager, load_agent_config
from acf.skills import SkillManager, format_skills_for_agent
from acf.store import SharedBoard, SimpleSharedBoard


# Base directory for all agents
AGENTS_DIR = Path(__file__).parent


def create_system_prompt(
    agent_name: str,
    skill_manager: SkillManager,
    workspace_manager: WorkspaceManager,
    shared_board: SharedBoard,
    enforced_skill: str | None = None,
) -> str:
    """Create system prompt from AGENT.md and skills.

    Args:
        agent_name: Name of the agent.
        skill_manager: SkillManager instance.
        workspace_manager: WorkspaceManager instance.
        shared_board: SharedBoard instance.
        enforced_skill: Optional skill to enforce.

    Returns:
        Complete system prompt for the agent.
    """
    # Load agent config from AGENT.md
    agent_dir = workspace_manager.get_agent_dir(agent_name)
    agent_config = load_agent_config(agent_dir)

    # Load skills
    skills = skill_manager.load_skills(agent_name)

    # Get shared context
    shared_context = shared_board.get_shared_context()

    # Build prompt
    prompt_parts = [
        "You are an AI agent with the following configuration:",
        "",
        "=" * 60,
    ]

    # Add identity
    if agent_config.get("identity"):
        prompt_parts.extend([
            f"## Identity",
            agent_config["identity"],
            "",
        ])

    # Add responsibilities
    if agent_config.get("responsibilities"):
        prompt_parts.append("## Responsibilities")
        for resp in agent_config["responsibilities"]:
            prompt_parts.append(f"- {resp}")
        prompt_parts.append("")

    # Add constraints
    if agent_config.get("constraints"):
        prompt_parts.append("## Constraints")
        for constraint in agent_config["constraints"]:
            prompt_parts.append(f"- {constraint}")
        prompt_parts.append("")

    prompt_parts.append("=" * 60)
    prompt_parts.append("")

    # Add skills section
    skills_section = format_skills_for_agent(skills, enforced_skill)
    if skills_section:
        prompt_parts.append(skills_section)
        prompt_parts.append("")

    # Add workspace info
    workspace = workspace_manager.get_agent_workspace(agent_name)
    prompt_parts.extend([
        "## Workspace",
        f"Your workspace is: {workspace}",
        "All files you create should be saved there.",
        "",
    ])

    # Add shared context
    if shared_context.get("deliverables"):
        prompt_parts.extend([
            "## Shared Deliverables",
            "The following deliverables have been shared by other agents:",
            "",
        ])
        for item in shared_context["deliverables"]:
            prompt_parts.append(f"- {item['key']} (by {item.get('author', 'unknown')})")
        prompt_parts.append("")

    # Add instructions
    prompt_parts.extend([
        "## Instructions",
        "1. Read the task carefully",
        "2. Check shared deliverables for relevant context",
        "3. Use your skills appropriately",
        "4. Save all outputs to your workspace",
        "5. Be concise and focused",
        "",
    ])

    return "\n".join(prompt_parts)


async def main():
    """Run the real agent workflow."""
    print("=" * 70)
    print("Real Agent Workflow: Software Development Pipeline")
    print("=" * 70)

    # Check for API key
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("\n⚠️  Warning: ANTHROPIC_API_KEY not set.")
        print("The Claude adapter may not work without it.")
        print("Continuing with available configuration...\n")

    # Initialize managers
    print("Initializing workspace and managers...")
    workspace_manager = WorkspaceManager(AGENTS_DIR)
    skill_manager = SkillManager(workspace_manager.agents_dir)

    # Use SimpleSharedBoard for compatibility (no LangGraph dependency required)
    shared_board = SimpleSharedBoard(team_id="dev_team_001")

    # Ensure directory structure exists
    agents = ["product_manager", "developer", "code_reviewer"]
    paths = workspace_manager.ensure_structure(agents=agents)
    print(f"  ✓ Workspace structure ensured")

    # Generate AGENT.md templates if they don't exist
    print("\nChecking AGENT.md configurations...")
    for agent_name in agents:
        agent_dir = workspace_manager.get_agent_dir(agent_name)
        agent_md = agent_dir / "AGENT.md"

        if not agent_md.exists():
            try:
                AgentTemplate.generate(
                    role=agent_name,
                    workspace=agent_dir,
                    exist_ok=True,
                )
                print(f"  ✓ Generated AGENT.md for {agent_name}")
            except ValueError as e:
                print(f"  ⚠️  Could not generate template for {agent_name}: {e}")
        else:
            print(f"  ✓ AGENT.md exists for {agent_name}")

    # Create default skills if they don't exist
    print("\nChecking skills...")
    _ensure_default_skills(skill_manager, agents)

    # Create adapters with system prompts
    print("\nCreating agents...")

    # Product Manager
    pm_workspace = workspace_manager.get_agent_workspace("product_manager")
    pm_adapter = create_claude_adapter(
        name="product_manager",
        workspace_dir=str(pm_workspace),
        timeout=120.0,
        confirm_delay=1.0,
    )
    pm_system_prompt = create_system_prompt(
        "product_manager",
        skill_manager,
        workspace_manager,
        shared_board,
        enforced_skill="write-prd",
    )
    print(f"  ✓ Product Manager (workspace: {pm_workspace})")

    # Developer
    dev_workspace = workspace_manager.get_agent_workspace("developer")
    dev_adapter = create_claude_adapter(
        name="developer",
        workspace_dir=str(dev_workspace),
        timeout=180.0,
        confirm_delay=1.0,
    )
    dev_system_prompt = create_system_prompt(
        "developer",
        skill_manager,
        workspace_manager,
        shared_board,
        enforced_skill="write-code",
    )
    print(f"  ✓ Developer (workspace: {dev_workspace})")

    # Code Reviewer
    reviewer_workspace = workspace_manager.get_agent_workspace("code_reviewer")
    reviewer_adapter = create_claude_adapter(
        name="code_reviewer",
        workspace_dir=str(reviewer_workspace),
        timeout=120.0,
        confirm_delay=1.0,
    )
    reviewer_system_prompt = create_system_prompt(
        "code_reviewer",
        skill_manager,
        workspace_manager,
        shared_board,
        enforced_skill="review-code",
    )
    print(f"  ✓ Code Reviewer (workspace: {reviewer_workspace})")

    # Build workflow
    print("\nBuilding workflow...")

    builder = WorkflowBuilder(
        "software_dev_pipeline",
        description="Multi-agent software development"
    )

    # Add nodes with system prompts and shared board integration
    builder.add_node(
        "write_prd",
        pm_adapter,
        system_prompt=pm_system_prompt,
        retry_count=2,
        timeout=120.0,
        transform_output=lambda result, state: _transform_output(
            result, state, "write_prd", shared_board, workspace_manager
        ),
    )

    builder.add_node(
        "implement",
        dev_adapter,
        system_prompt=dev_system_prompt,
        retry_count=2,
        timeout=180.0,
        transform_output=lambda result, state: _transform_output(
            result, state, "implement", shared_board, workspace_manager
        ),
    )

    builder.add_node(
        "review",
        reviewer_adapter,
        system_prompt=reviewer_system_prompt,
        retry_count=2,
        timeout=120.0,
        transform_output=lambda result, state: _transform_output(
            result, state, "review", shared_board, workspace_manager
        ),
    )

    # Define flow
    builder.add_edge("write_prd", "implement")
    builder.add_edge("implement", "review")
    builder.add_edge("review", END)

    builder.set_entry_point("write_prd")

    print("  ✓ Workflow configured")

    # Compile and run
    graph = builder.compile()
    runner = WorkflowRunner(graph, workflow_id="dev_pipeline_001")

    # Event monitoring
    def on_event(event):
        emoji = {
            WorkflowEventType.NODE_STARTED: "▶️",
            WorkflowEventType.NODE_COMPLETED: "✅",
            WorkflowEventType.NODE_ERROR: "❌",
            WorkflowEventType.CHECKPOINT_SAVED: "💾",
        }.get(event.event_type, "•")

        if event.node_name:
            print(f"{emoji} {event.node_name}: {event.event_type.name}")
        else:
            print(f"{emoji} Workflow: {event.event_type.name}")

    runner.add_callback(on_event)

    # Run with a feature request
    print("\n" + "-" * 70)
    print("Starting development pipeline...")
    print("-" * 70)

    feature_request = """
Create a simple task management CLI tool with the following features:

1. Add tasks with title, description, and priority
2. List all tasks with filtering by status/priority
3. Mark tasks as complete
4. Delete tasks
5. Persist tasks to a JSON file

Requirements:
- Use Python 3.10+
- Use Click for CLI interface
- Include proper error handling
- Include unit tests with pytest
- Follow PEP 8 style

Save all code to your workspace directory.
"""

    try:
        result = await runner.run(feature_request)

        print("\n" + "=" * 70)
        print("Pipeline Complete")
        print("=" * 70)
        print(f"Status: {result.status}")
        print(f"Success: {result.success}")
        print(f"Execution Time: {result.execution_time:.2f}s")
        print(f"Nodes Executed: {result.node_count}")

        if result.error:
            print(f"\nError: {result.error}")

        # Check workspaces for outputs
        print("\n" + "-" * 70)
        print("Checking agent outputs...")
        print("-" * 70)

        for agent_name in agents:
            workspace = workspace_manager.get_agent_workspace(agent_name)
            files = workspace_manager.get_agent_files(agent_name, "workspace")

            print(f"\n{agent_name}:")
            if files:
                for f in files:
                    size = f.stat().st_size if f.is_file() else "dir"
                    print(f"  - {f.name} ({size} bytes)" if isinstance(size, int) else f"  - {f.name}/")
            else:
                print("  (no files)")

        # Check shared deliverables
        print("\n" + "-" * 70)
        print("Shared Deliverables:")
        print("-" * 70)
        shared_context = shared_board.get_shared_context()
        for item in shared_context.get("deliverables", []):
            print(f"  - {item['key']} (by {item.get('author', 'unknown')})")

        # Export workspace info
        info_file = workspace_manager.export_workspace_info()
        print(f"\nWorkspace info exported to: {info_file}")

        print("\n" + "=" * 70)

    except Exception as e:
        print(f"\n❌ Workflow failed: {e}")
        import traceback
        traceback.print_exc()


def _transform_output(result, state, node_name, shared_board, workspace_manager):
    """Transform agent output and write to shared board.

    Args:
        result: Agent execution result.
        state: Current workflow state.
        node_name: Name of the current node.
        shared_board: SharedBoard instance.
        workspace_manager: WorkspaceManager instance.

    Returns:
        State updates dictionary.
    """
    from acf.adapter.base import AgentStatus

    updates = {
        "messages": list(state.get("messages", [])),
        "context": dict(state.get("context", {})),
    }

    if result.status == AgentStatus.COMPLETED:
        # Add assistant message
        updates["messages"].append({
            "role": "assistant",
            "content": result.output,
            "node": node_name,
            "metadata": result.metadata,
        })

        # Update context
        updates["context"][f"{node_name}_output"] = result.output

        # Write to shared board based on node type
        if node_name == "write_prd":
            shared_board.put(
                namespace=("team", "deliverables"),
                key="prd",
                value={
                    "content": result.output,
                    "status": "draft",
                },
                author="product_manager",
            )
        elif node_name == "implement":
            shared_board.put(
                namespace=("team", "deliverables"),
                key="implementation",
                value={
                    "content": result.output,
                    "status": "completed",
                },
                author="developer",
            )
        elif node_name == "review":
            shared_board.put(
                namespace=("team", "deliverables"),
                key="review_report",
                value={
                    "content": result.output,
                    "status": "completed",
                },
                author="code_reviewer",
            )

    elif result.status == AgentStatus.ERROR:
        updates["error"] = {
            "node": node_name,
            "message": result.error or "Unknown error",
            "status": result.status.value,
        }

    return updates


def _ensure_default_skills(skill_manager: SkillManager, agents: list):
    """Ensure default skills exist for all agents.

    Args:
        skill_manager: SkillManager instance.
        agents: List of agent names.
    """
    # Product Manager skills
    if "product_manager" in agents:
        skills = skill_manager.list_skills("product_manager")
        if "write-prd" not in skills:
            skill_manager.create_skill(
                agent_name="product_manager",
                skill_name="write-prd",
                description="编写产品需求文档",
                when_to_use="当需要为新功能编写 PRD 时使用",
                inputs=[
                    "feature_name: 功能名称",
                    "target_users: 目标用户",
                    "requirements: 功能需求",
                ],
                outputs=[
                    "PRD 文档 (Markdown 格式)",
                    "验收标准",
                ],
                steps=[
                    "理解功能背景和目标用户",
                    "编写产品概述",
                    "列出功能列表",
                    "定义验收标准",
                    "保存 PRD 到 workspace",
                ],
            )
            print("  ✓ Created write-prd skill for product_manager")

        if "analyze-requirements" not in skills:
            skill_manager.create_skill(
                agent_name="product_manager",
                skill_name="analyze-requirements",
                description="分析用户需求",
                when_to_use="当需要深入理解用户需求时使用",
                inputs=[
                    "user_request: 用户原始需求",
                ],
                outputs=[
                    "需求分析报告",
                    "功能建议列表",
                ],
                steps=[
                    "提取核心需求",
                    "识别隐含需求",
                    "分析可行性",
                    "输出功能建议",
                ],
            )
            print("  ✓ Created analyze-requirements skill for product_manager")

    # Developer skills
    if "developer" in agents:
        skills = skill_manager.list_skills("developer")
        if "write-code" not in skills:
            skill_manager.create_skill(
                agent_name="developer",
                skill_name="write-code",
                description="编写高质量代码",
                when_to_use="当需要根据 PRD 实现功能时使用",
                inputs=[
                    "prd: 产品需求文档",
                    "tech_stack: 技术栈要求",
                ],
                outputs=[
                    "实现代码",
                    "代码注释",
                ],
                steps=[
                    "阅读 PRD 文档",
                    "设计代码结构",
                    "实现核心功能",
                    "添加错误处理",
                    "保存代码到 workspace",
                ],
            )
            print("  ✓ Created write-code skill for developer")

        if "write-tests" not in skills:
            skill_manager.create_skill(
                agent_name="developer",
                skill_name="write-tests",
                description="编写单元测试",
                when_to_use="当需要为代码编写测试时使用",
                inputs=[
                    "code_files: 代码文件列表",
                    "test_framework: 测试框架 (如 pytest)",
                ],
                outputs=[
                    "测试代码",
                    "测试报告",
                ],
                steps=[
                    "分析代码功能",
                    "设计测试用例",
                    "编写测试代码",
                    "运行测试验证",
                ],
            )
            print("  ✓ Created write-tests skill for developer")

    # Code Reviewer skills
    if "code_reviewer" in agents:
        skills = skill_manager.list_skills("code_reviewer")
        if "review-code" not in skills:
            skill_manager.create_skill(
                agent_name="code_reviewer",
                skill_name="review-code",
                description="审查代码质量",
                when_to_use="当需要检查代码质量和规范时使用",
                inputs=[
                    "code_files: 代码文件列表",
                    "requirements: 需求文档",
                ],
                outputs=[
                    "代码审查报告",
                    "改进建议列表",
                ],
                steps=[
                    "阅读需求和代码",
                    "检查代码规范",
                    "识别潜在问题",
                    "评估代码质量",
                    "生成审查报告",
                ],
            )
            print("  ✓ Created review-code skill for code_reviewer")

        if "check-style" not in skills:
            skill_manager.create_skill(
                agent_name="code_reviewer",
                skill_name="check-style",
                description="检查代码风格",
                when_to_use="当需要检查代码风格规范时使用",
                inputs=[
                    "code_files: 代码文件列表",
                    "style_guide: 风格指南 (如 PEP 8)",
                ],
                outputs=[
                    "风格检查报告",
                    "格式问题列表",
                ],
                steps=[
                    "检查缩进和空白",
                    "检查命名规范",
                    "检查导入顺序",
                    "生成风格报告",
                ],
            )
            print("  ✓ Created check-style skill for code_reviewer")


if __name__ == "__main__":
    # Show what will happen
    print("""
This example demonstrates a real multi-agent workflow with:

1. Product Manager
   - Reads: AGENT.md (role definition)
   - Has skills: write-prd, analyze-requirements
   - Workspace: agents/product_manager/workspace/
   - Task: Write PRD for the CLI tool

2. Developer
   - Reads: AGENT.md (role definition)
   - Has skills: write-code, write-tests
   - Workspace: agents/developer/workspace/
   - Task: Read PRD and implement the code

3. Code Reviewer
   - Reads: AGENT.md (role definition)
   - Has skills: review-code, check-style
   - Workspace: agents/code_reviewer/workspace/
   - Task: Review the implementation

Features:
- WorkspaceManager: Manages directory structure
- AgentTemplate: Generates AGENT.md if not exists
- SkillManager: Loads and manages skills
- SharedBoard: Enables agent-to-agent communication

Each agent uses Claude Code (via tmux) with its own workspace.
""")

    response = input("\nProceed? [Y/n]: ").strip().lower()
    if response in ("", "y", "yes"):
        asyncio.run(main())
    else:
        print("Aborted.")
